version: '3.1'
services:
  #BANCO DE DADOS MYSQL
  db:
    container_name: generic_database
    build: ./db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./db/database:/var/lib/mysql
    ports:
      - "3306:3306"
  #PHPMYADMIN PARA O BANCO DE DADOS
  phpmyadmin:
    container_name: generic_phpmyadmin
    build: ./phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=123
    ports:
      - "8000:80"
    depends_on:
      - db