version: '3.1'
services:
  #BANCO DE DADOS MYSQL
  db:
    container_name: database
    build: ./db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./db/database:/var/lib/mysql
    ports:
      - "3306:3306"
  #PHPMYADMIN PARA O BANCO DE DADOS
  phpmyadmin:
    container_name: pma
    build: ./phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=123
      - UPLOAD_LIMIT=300M
    ports:
      - "8888:80"
    depends_on:
      - db